apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dk3uzmk7n-nodejs
  janus-idp.io/tekton: dk3uzmk7n-nodejs
  backstage.io/kubernetes-id: dk3uzmk7n-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dk3uzmk7n-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
